### ISSUE TITLE
(migration) error when upgrading from 0.8.13 to 0.9.x

### ISSUE THREAD

**Issue by wfehr** [nephila/djangocms-blog#441]
I am currently using djangocms-blog version 0.8.13 and wanted to upgrade it to a 0.9.x version.
The problem is that the migration I am depending on isn't existing in version 0.9.x.
Specific:
- v0.8.13 -> 0022_auto_20170304_1040.py
- v0.9.x -> 0022_auto_20160605_2305.py
(as I just saw: 0.8.13 is not available in github, but in pypi. Nevertheless the wrong migration is also available in 0.8.12)

I tried the following steps:
- migrate djangocms_blog to 0021 (this also reverts my migration with the dependency)
- install the new version
- migrate the new version of djangocms_blog
 - error: meta_description entries are too long ~~(fixed with deleting the data in djangocms_blog_post_translation.meta_description)~~
 - ~~error: djangocms_blog_post_related already exists~~

Is there already a way to upgrade this which solves this problems (and maybe some others) and keeps the data?

Thanks already.

**Comment by yakky** [comment]
Thanks @wfehr for reporting this. Indeed, a migration from 0.8 branch has not been ported to 0.9 :man_facepalming: 
We will release a 0.9 version that integrate this. Would you be willing to test a PR that fixes this?

**Comment by yakky** [comment]
@wfehr could you test the linked PR? (0.8.13 was pushed on release but apparently not the tag, only the tip of `release/0.8.x` branch. This is now fixed, thanks again)

**Comment by wfehr** [comment]
updated the issue description because the second error with "post_related" was my fault, I didn't reset the database correctly.

At the moment I am still getting an error when migrating djangocms_blog:

>   Applying djangocms_blog.0031_auto_20170610_1744... OK
>   Applying djangocms_blog.0032_auto_20180109_0023...Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   [...]
>   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
>     _mysql.connection.query(self, query)
> _mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
>   [...]

I deleted the data in 'djangocms_blog_post_translation' but still got the same error.

**Comment by wfehr** [comment]
> Currently having some other issues right now with the categories and posts. But I am not sure if it is again a problem of mine, still trying to find out.
Yep, these are problems of mine. Needed to add "sortedm2m" to INSTALLED_APPS and change my template for the menu.

Looks good, thanks @yakky for the work :+1:

**Comment by yakky** [comment]
@wfehr thanks for checking! A new release is on the way
